export { default as AccordionOne } from '../../components/AccordionOne.vue'
export { default as FunFact } from '../../components/FunFact.vue'
export { default as InstagramPost } from '../../components/InstagramPost.vue'
export { default as About } from '../../components/about-us-one/About.vue'
export { default as AboutUsOneFunFact } from '../../components/about-us-one/FunFact.vue'
export { default as AboutUsOneInstructor } from '../../components/about-us-one/Instructor.vue'
export { default as AboutUsOneWhyChoose } from '../../components/about-us-one/WhyChoose.vue'
export { default as AboutUsThreeContactInfo } from '../../components/about-us-three/ContactInfo.vue'
export { default as AboutUsThreeFunFact } from '../../components/about-us-three/FunFact.vue'
export { default as AboutUsThreeInstructor } from '../../components/about-us-three/Instructor.vue'
export { default as AboutUsThreeTestimonial } from '../../components/about-us-three/Testimonial.vue'
export { default as AboutUsThreeWhyChoose } from '../../components/about-us-three/WhyChoose.vue'
export { default as AnimationMouseMove } from '../../components/animation/MouseMove.vue'
export { default as CommonBreadCrumbOne } from '../../components/common/BreadCrumbOne.vue'
export { default as CommonBreadCrumbThree } from '../../components/common/BreadCrumbThree.vue'
export { default as CommonBreadCrumbTwo } from '../../components/common/BreadCrumbTwo.vue'
export { default as CommonColorMode } from '../../components/common/ColorMode.vue'
export { default as CommonPaginationOne } from '../../components/common/PaginationOne.vue'
export { default as CommonSectionTitle } from '../../components/common/SectionTitle.vue'
export { default as AboutUsTwoFeatures } from '../../components/about-us-two/Features.vue'
export { default as AboutUsTwoFunFact } from '../../components/about-us-two/FunFact.vue'
export { default as AboutUsTwoInstructor } from '../../components/about-us-two/Instructor.vue'
export { default as AboutUsTwoLogo } from '../../components/about-us-two/Logo.vue'
export { default as AboutUsTwoTestimonial } from '../../components/about-us-two/Testimonial.vue'
export { default as AboutUsTwoVideo } from '../../components/about-us-two/Video.vue'
export { default as BlogPostList } from '../../components/blog/BlogPostList.vue'
export { default as BlogPostOne } from '../../components/blog/BlogPostOne.vue'
export { default as BlogPostStandard } from '../../components/blog/BlogPostStandard.vue'
export { default as BlogPostTwo } from '../../components/blog/BlogPostTwo.vue'
export { default as CourseTypeEight } from '../../components/course/CourseTypeEight.vue'
export { default as CourseTypeFive } from '../../components/course/CourseTypeFive.vue'
export { default as CourseTypeFour } from '../../components/course/CourseTypeFour.vue'
export { default as CourseTypeOne } from '../../components/course/CourseTypeOne.vue'
export { default as CourseTypeSeven } from '../../components/course/CourseTypeSeven.vue'
export { default as CourseTypeSix } from '../../components/course/CourseTypeSix.vue'
export { default as CourseTypeThree } from '../../components/course/CourseTypeThree.vue'
export { default as CourseTypeTwo } from '../../components/course/CourseTypeTwo.vue'
export { default as CtaCTAOne } from '../../components/cta/CTAOne.vue'
export { default as CtaCTAOneAlter } from '../../components/cta/CTAOneAlter.vue'
export { default as EventList } from '../../components/event/EventList.vue'
export { default as EventOne } from '../../components/event/EventOne.vue'
export { default as EventSectionOne } from '../../components/event/EventSectionOne.vue'
export { default as EventTwo } from '../../components/event/EventTwo.vue'
export { default as FooterKindergarten } from '../../components/footer/FooterKindergarten.vue'
export { default as FooterKitchen } from '../../components/footer/FooterKitchen.vue'
export { default as FooterLanding } from '../../components/footer/FooterLanding.vue'
export { default as FooterOne } from '../../components/footer/FooterOne.vue'
export { default as FooterThree } from '../../components/footer/FooterThree.vue'
export { default as FooterTwo } from '../../components/footer/FooterTwo.vue'
export { default as FooterYoga } from '../../components/footer/FooterYoga.vue'
export { default as FooterGoogleMapWithAPI } from '../../components/footer/GoogleMapWithAPI.vue'
export { default as FooterScrollToTop } from '../../components/footer/ScrollToTop.vue'
export { default as HeaderCategory } from '../../components/header/Category.vue'
export { default as HeaderFour } from '../../components/header/HeaderFour.vue'
export { default as HeaderLanding } from '../../components/header/HeaderLanding.vue'
export { default as HeaderOne } from '../../components/header/HeaderOne.vue'
export { default as HeaderThree } from '../../components/header/HeaderThree.vue'
export { default as HeaderTopOne } from '../../components/header/HeaderTopOne.vue'
export { default as HeaderTopTwo } from '../../components/header/HeaderTopTwo.vue'
export { default as HeaderTwo } from '../../components/header/HeaderTwo.vue'
export { default as HeaderMobileMenu } from '../../components/header/MobileMenu.vue'
export { default as HeaderNavigation } from '../../components/header/Navigation.vue'
export { default as HeaderOffCanvasMobileMenuOne } from '../../components/header/OffCanvasMobileMenuOne.vue'
export { default as HeaderOffCanvasMobileMenuTwo } from '../../components/header/OffCanvasMobileMenuTwo.vue'
export { default as HeaderSearchPopUp } from '../../components/header/SearchPopUp.vue'
export { default as HomeDistantLearningAbout } from '../../components/home-distant-learning/About.vue'
export { default as HomeDistantLearningBanner } from '../../components/home-distant-learning/Banner.vue'
export { default as HomeDistantLearningBlog } from '../../components/home-distant-learning/Blog.vue'
export { default as HomeDistantLearningCategories } from '../../components/home-distant-learning/Categories.vue'
export { default as HomeDistantLearningCourse } from '../../components/home-distant-learning/Course.vue'
export { default as HomeDistantLearningFAQ } from '../../components/home-distant-learning/FAQ.vue'
export { default as HomeDistantLearningFunFact } from '../../components/home-distant-learning/FunFact.vue'
export { default as HomeDistantLearningLogo } from '../../components/home-distant-learning/Logo.vue'
export { default as HomeDistantLearningVideo } from '../../components/home-distant-learning/Video.vue'
export { default as HomeKindergartenAbout } from '../../components/home-kindergarten/About.vue'
export { default as HomeKindergartenActivities } from '../../components/home-kindergarten/Activities.vue'
export { default as HomeKindergartenBanner } from '../../components/home-kindergarten/Banner.vue'
export { default as HomeKindergartenBlog } from '../../components/home-kindergarten/Blog.vue'
export { default as HomeKindergartenCourse } from '../../components/home-kindergarten/Course.vue'
export { default as HomeKindergartenEvent } from '../../components/home-kindergarten/Event.vue'
export { default as HomeKindergartenFAQ } from '../../components/home-kindergarten/FAQ.vue'
export { default as HomeKindergartenSubscriptionForm } from '../../components/home-kindergarten/SubscriptionForm.vue'
export { default as HomeKitchenCoachAbout } from '../../components/home-kitchen-coach/About.vue'
export { default as HomeKitchenCoachBanner } from '../../components/home-kitchen-coach/Banner.vue'
export { default as HomeKitchenCoachBlog } from '../../components/home-kitchen-coach/Blog.vue'
export { default as HomeKitchenCoachCTA } from '../../components/home-kitchen-coach/CTA.vue'
export { default as HomeKitchenCoachCourse } from '../../components/home-kitchen-coach/Course.vue'
export { default as HomeKitchenCoachFAQ } from '../../components/home-kitchen-coach/FAQ.vue'
export { default as HomeKitchenCoachFeatures } from '../../components/home-kitchen-coach/Features.vue'
export { default as HomeKitchenCoachFunFact } from '../../components/home-kitchen-coach/FunFact.vue'
export { default as HomeKitchenCoachInstagram } from '../../components/home-kitchen-coach/Instagram.vue'
export { default as HomeKitchenCoachInstructor } from '../../components/home-kitchen-coach/Instructor.vue'
export { default as HomeKitchenCoachLogo } from '../../components/home-kitchen-coach/Logo.vue'
export { default as HomeKitchenCoachTestimonial } from '../../components/home-kitchen-coach/Testimonial.vue'
export { default as HomeLandingDemoBanner } from '../../components/home-landing-demo/Banner.vue'
export { default as HomeLandingDemoCourseLayout } from '../../components/home-landing-demo/CourseLayout.vue'
export { default as HomeLandingDemoFeatures } from '../../components/home-landing-demo/Features.vue'
export { default as HomeLandingDemoFunFact } from '../../components/home-landing-demo/FunFact.vue'
export { default as HomeDemo } from '../../components/home-landing-demo/HomeDemo.vue'
export { default as HomeLandingDemoInnerPages } from '../../components/home-landing-demo/InnerPages.vue'
export { default as HomeLandingDemoLearnWith } from '../../components/home-landing-demo/LearnWith.vue'
export { default as HomeLandingDemoShopLayout } from '../../components/home-landing-demo/ShopLayout.vue'
export { default as HomeMainAbout } from '../../components/home-main/About.vue'
export { default as HomeMainBanner } from '../../components/home-main/Banner.vue'
export { default as HomeMainBlog } from '../../components/home-main/Blog.vue'
export { default as HomeMainCategories } from '../../components/home-main/Categories.vue'
export { default as HomeMainContactInfo } from '../../components/home-main/ContactInfo.vue'
export { default as HomeMainCourse } from '../../components/home-main/Course.vue'
export { default as HomeMainFeatures } from '../../components/home-main/Features.vue'
export { default as HomeMainFunFact } from '../../components/home-main/FunFact.vue'
export { default as HomeMainInstructor } from '../../components/home-main/Instructor.vue'
export { default as HomeOnlineAcademyBanner } from '../../components/home-online-academy/Banner.vue'
export { default as HomeOnlineAcademyBlog } from '../../components/home-online-academy/Blog.vue'
export { default as HomeOnlineAcademyCategories } from '../../components/home-online-academy/Categories.vue'
export { default as HomeOnlineAcademyContactInfo } from '../../components/home-online-academy/ContactInfo.vue'
export { default as HomeOnlineAcademyCourse } from '../../components/home-online-academy/Course.vue'
export { default as HomeOnlineAcademyFAQ } from '../../components/home-online-academy/FAQ.vue'
export { default as HomeOnlineAcademyFunFact } from '../../components/home-online-academy/FunFact.vue'
export { default as HomeOnlineAcademyInstructor } from '../../components/home-online-academy/Instructor.vue'
export { default as HomeUniversityAbout } from '../../components/home-university/About.vue'
export { default as HomeUniversityBanner } from '../../components/home-university/Banner.vue'
export { default as HomeUniversityCampus } from '../../components/home-university/Campus.vue'
export { default as HomeUniversityContactInfo } from '../../components/home-university/ContactInfo.vue'
export { default as HomeUniversityCourse } from '../../components/home-university/Course.vue'
export { default as HomeUniversityFeatures } from '../../components/home-university/Features.vue'
export { default as HomeUniversityFunFact } from '../../components/home-university/FunFact.vue'
export { default as HomeUniversityVideo } from '../../components/home-university/Video.vue'
export { default as HomeYogaInstructorAbout } from '../../components/home-yoga-instructor/About.vue'
export { default as HomeYogaInstructorBanner } from '../../components/home-yoga-instructor/Banner.vue'
export { default as HomeYogaInstructorCourse } from '../../components/home-yoga-instructor/Course.vue'
export { default as HomeYogaInstructorFunFact } from '../../components/home-yoga-instructor/FunFact.vue'
export { default as HomeYogaInstructorInstagram } from '../../components/home-yoga-instructor/Instagram.vue'
export { default as HomeYogaInstructor } from '../../components/home-yoga-instructor/Instructor.vue'
export { default as HomeYogaInstructorTestimonial } from '../../components/home-yoga-instructor/Testimonial.vue'
export { default as HomeYogaInstructorVideo } from '../../components/home-yoga-instructor/Video.vue'
export { default as HomeYogaInstructorWhyChoose } from '../../components/home-yoga-instructor/WhyChoose.vue'
export { default as InstructorFive } from '../../components/instructor/InstructorFive.vue'
export { default as InstructorFour } from '../../components/instructor/InstructorFour.vue'
export { default as InstructorOne } from '../../components/instructor/InstructorOne.vue'
export { default as InstructorThree } from '../../components/instructor/InstructorThree.vue'
export { default as InstructorTwo } from '../../components/instructor/InstructorTwo.vue'
export { default as LogoOne } from '../../components/logo/LogoOne.vue'
export { default as LogoTwo } from '../../components/logo/LogoTwo.vue'
export { default as ProductOne } from '../../components/product/ProductOne.vue'
export { default as SidebarBlogSidebarOne } from '../../components/sidebar/BlogSidebarOne.vue'
export { default as SidebarCourseSidebarOne } from '../../components/sidebar/CourseSidebarOne.vue'
export { default as SidebarEventSidebar } from '../../components/sidebar/EventSidebar.vue'
export { default as SidebarPageSidebarOne } from '../../components/sidebar/PageSidebarOne.vue'
export { default as TestimonialOne } from '../../components/testimonial/TestimonialOne.vue'
export { default as TestimonialThree } from '../../components/testimonial/TestimonialThree.vue'
export { default as TestimonialTwo } from '../../components/testimonial/TestimonialTwo.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
